sudo: false
language: python

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=py36

install:
  - pip install tox

script:
  - tox -e $TOX_ENV

before_cache:
  - rm -rm $HOME/.cache/pip/log

cache:
  directories:
    - $HOME/.cache/pip
